# Generated by Django 3.2.9 on 2021-11-03 11:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('length', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(1)])),
                ('route_grade', models.CharField(max_length=30)),
                ('route_grade_self', models.CharField(max_length=30)),
                ('comment', models.TextField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
