# Generated by Django 3.2.9 on 2021-11-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='climbingroutes',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
