# Generated by Django 3.2.9 on 2021-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20211104_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaCategory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='climbingroutes',
            name='category',
            field=models.CharField(default='Rocks', max_length=100),
        ),
    ]
