# Generated by Django 3.2.9 on 2021-11-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_climbingroutes_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.category')),
            ],
        ),
    ]
