# Generated by Django 3.2.9 on 2021-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_routegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingroutes',
            name='official_grade',
            field=models.ForeignKey(default='0', on_delete=models.SET('0'), to='routes.routegrade'),
        ),
    ]
