# Generated by Django 3.2.9 on 2021-11-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_climbingroutes_official_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingroutes',
            name='official_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.routegrade'),
        ),
    ]
