# Generated by Django 3.2.9 on 2021-11-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_climbingroutes_official_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbingroutes',
            name='official_grade',
        ),
    ]
