# Generated by Django 3.2.9 on 2021-11-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_remove_climbingroutes_official_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingroutes',
            name='official_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.routegrade'),
        ),
    ]
