# Generated by Django 3.2.9 on 2021-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_climbingroutes_official_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingroutes',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
