# Generated by Django 3.2.9 on 2021-11-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_alter_climbingroutes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbingroutes',
            name='route_grade',
        ),
    ]
