# Generated by Django 3.2.9 on 2021-12-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_remove_climbingroutes_route_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingroutes',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='routegrade',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='routes.category'),
        ),
    ]
