# Generated by Django 3.2.9 on 2021-12-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_auto_20211202_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingroutes',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
