# Generated by Django 3.2.9 on 2021-12-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_alter_climbingroutes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='routegrade',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
