# Generated by Django 3.2.9 on 2021-12-12 15:49

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0018_routegrade_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingroutes',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
    ]
