# Generated by Django 3.2.9 on 2021-12-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0019_climbingroutes_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingroutes',
            name='style',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
